version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/go:1-1.22-bookworm
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      SSL_MODE: disable
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data: